# Generated by Django 5.2.13 on 2026-04-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_permissions_catalog",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("password_change_tz", models.BigIntegerField(blank=True, null=True)),
                ("app_lang", models.CharField(blank=True, max_length=255, null=True)),
                ("reset_token", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("system_settings", models.JSONField(blank=True, null=True)),
                ("sort", models.BigIntegerField(blank=True, null=True)),
                ("created_by_id", models.BigIntegerField(blank=True, null=True)),
                ("updated_by_id", models.BigIntegerField(blank=True, null=True)),
                ("teacher_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("opt_school_year", models.CharField(blank=True, max_length=255, null=True)),
                ("level_rank", models.FloatField(blank=True, null=True)),
                ("login_token", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("login_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("portal_password", models.CharField(blank=True, max_length=255, null=True)),
                ("opt_class_id", models.BigIntegerField(blank=True, null=True)),
                ("opt_student_id", models.BigIntegerField(blank=True, null=True)),
                ("main_department_id", models.BigIntegerField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("groups", models.ManyToManyField(blank=True, related_name="user_set", related_query_name="user", to="auth.group")),
                ("user_permissions", models.ManyToManyField(blank=True, related_name="user_set", related_query_name="user", to="auth.permission")),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_roles", to="users.permission")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_permissions", to="users.role")),
            ],
            options={
                "db_table": "user_role_permissions",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_user_roles", to="users.user")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_users", to="users.role")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_roles", to="users.user")),
            ],
            options={
                "db_table": "user_role_assignments",
                "unique_together": {("user", "role")},
            },
        ),
    ]
