# Generated by Codex on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


def seed_local_authz(apps, schema_editor):
    LocalPermission = apps.get_model("users", "LocalPermission")
    LocalRole = apps.get_model("users", "LocalRole")
    LocalRolePermission = apps.get_model("users", "LocalRolePermission")

    permissions = [
        ("teacher.view", "View teachers", "View teacher profiles and rosters."),
        ("teacher.manage", "Manage teachers", "Create and update teacher profiles."),
        ("schedule.view", "View schedules", "View teaching schedules."),
        ("schedule.manage", "Manage schedules", "Create and update schedules."),
        ("center.view", "View center data", "View center-scoped teaching data."),
        ("center.manage", "Manage center data", "Manage center-scoped teaching data."),
        ("access.manage", "Manage access", "Manage local roles and permissions."),
    ]
    permission_map = {}
    for code, name, description in permissions:
        permission, _ = LocalPermission.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )
        permission_map[code] = permission

    roles = {
        "admin": {
            "name": "Admin",
            "description": "Full access in teacher service.",
            "permissions": [
                "teacher.view",
                "teacher.manage",
                "schedule.view",
                "schedule.manage",
                "center.view",
                "center.manage",
                "access.manage",
            ],
        },
        "center_manager": {
            "name": "Center Manager",
            "description": "Manage teacher service data for assigned centers.",
            "permissions": [
                "teacher.view",
                "teacher.manage",
                "schedule.view",
                "schedule.manage",
                "center.view",
                "center.manage",
            ],
        },
        "teacher": {
            "name": "Teacher",
            "description": "Access own teacher information and schedules.",
            "permissions": [
                "teacher.view",
                "schedule.view",
            ],
        },
    }

    for code, config in roles.items():
        role, _ = LocalRole.objects.get_or_create(
            code=code,
            defaults={
                "name": config["name"],
                "description": config["description"],
                "is_active": True,
            },
        )
        for permission_code in config["permissions"]:
            LocalRolePermission.objects.get_or_create(
                role=role,
                permission=permission_map[permission_code],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nocobase_user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "service_users"},
        ),
        migrations.CreateModel(
            name="LocalPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "local_permissions"},
        ),
        migrations.CreateModel(
            name="LocalRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "local_roles"},
        ),
        migrations.CreateModel(
            name="LocalRolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles_map", to="users.localpermission")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permissions_map", to="users.localrole")),
            ],
            options={"db_table": "local_role_permissions", "unique_together": {("role", "permission")}},
        ),
        migrations.CreateModel(
            name="LocalUserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_assignments", to="users.localrole")),
                ("service_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_assignments", to="users.serviceuser")),
            ],
            options={"db_table": "local_user_roles", "unique_together": {("service_user", "role")}},
        ),
        migrations.RunPython(seed_local_authz, migrations.RunPython.noop),
    ]
