# Generated by Django 5.2.13 on 2026-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=20)),
                ('gio_bat_dau', models.TimeField()),
                ('gio_ket_thuc', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CoSoDaoTao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_co_so', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_day', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LichDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=50, unique=True)),
                ('mon_hoc', models.CharField(max_length=255)),
                ('ten_lop', models.CharField(max_length=255)),
                ('khoi', models.PositiveSmallIntegerField()),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('trang_thai', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgayLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_co_the', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('gio_ket_thuc', models.TimeField()),
            ],
        ),
    ]
