# Generated by Django 5.2.13 on 2026-04-09 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_vien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lichday',
            name='ca_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_days', to='app.caday'),
        ),
        migrations.AddField(
            model_name='lichday',
            name='giao_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_days', to='app.giaovien'),
        ),
        migrations.AddField(
            model_name='lop',
            name='co_so_dao_tao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lops', to='app.cosodaotao'),
        ),
        migrations.AddField(
            model_name='caday',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_days', to='app.lop'),
        ),
        migrations.AddField(
            model_name='ngaylamviec',
            name='giao_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngay_lam_viecs', to='app.giaovien'),
        ),
    ]
