# Generated by Django 5.2.13 on 2026-04-09 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lop',
            name='khoi',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='lop',
            name='trang_thai',
            field=models.CharField(choices=[('dang_mo', 'Dang mo'), ('dang_hoc', 'Dang hoc'), ('tam_dung', 'Tam dung'), ('da_ket_thuc', 'Da ket thuc')], default='dang_mo', max_length=50),
        ),
    ]
