# Generated by Django 5.2.13 on 2026-04-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lop_khoi_alter_lop_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaovien',
            name='ngay_day',
        ),
    ]
